# Generated by Django 3.0.7 on 2020-07-06 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20200705_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='loc',
            new_name='geom',
        ),
    ]
